# Generated by Django 3.2.7 on 2022-04-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeName', models.CharField(max_length=30)),
                ('summary', models.TextField()),
                ('nationName', models.CharField(max_length=30)),
                ('typeName', models.CharField(max_length=30)),
                ('cookingTime', models.IntegerField()),
                ('calorie', models.IntegerField()),
                ('QNT', models.IntegerField()),
                ('level', models.CharField(max_length=10)),
                ('idrType', models.CharField(max_length=20, null=True)),
                ('image', models.TextField()),
            ],
        ),
    ]
