# Generated by Django 3.2.7 on 2022-05-03 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeName', models.CharField(max_length=30)),
                ('summary', models.TextField()),
                ('cookingTime', models.IntegerField()),
                ('calorie', models.IntegerField()),
                ('QNT', models.IntegerField()),
                ('level', models.CharField(max_length=10)),
                ('idrType', models.CharField(max_length=20, null=True)),
                ('image', models.TextField()),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Maincategory.nation')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Maincategory.type')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('cooking_dc', models.TextField()),
                ('step_img', models.TextField(null=True)),
                ('step_tip', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Maincategory.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irdnt_name', models.CharField(max_length=20)),
                ('irdnt_cpcty', models.CharField(max_length=10)),
                ('irdnt_ty_nm', models.CharField(max_length=20)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Maincategory.recipe')),
            ],
        ),
    ]
