# Generated by Django 3.2.7 on 2022-04-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maincategory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
